# peryf config
CONFIG_SPI=y
CONFIG_GPIO=y
# components config
CONFIG_SENSOR=y
CONFIG_DHT=y
CONFIG_DISPLAY=y
CONFIG_MAX7219=y
# console config
CONFIG_PRINTK=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# networking config
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_HTTP_CLIENT=y

# increase stack memoy to avoid crashes
CONFIG_MAIN_STACK_SIZE=4096

# enable wifi
CONFIG_WIFI=y

# get ipv4 addres from dhcp
CONFIG_NET_DHCPV4=y

#enbale dns resolver
CONFIG_DNS_RESOLVER=y

# how long to wait for dhcp to provide an ip adress (in seconds)
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_INIT_TIMEOUT=30

# network debug config
CONFIG_NET_LOG=y

# network managment
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_MGMT_EVENT_STACK_SIZE=1024
